### PR TITLE
Fix up default enconfig name

### LINKED ISSUE #1917: Helm chart compatibility with EKS docs
**What happened**:

I've been following the [CNI custom networking instructions](https://docs.aws.amazon.com/eks/latest/userguide/cni-custom-network.html) in the EKS docs.

Step 5c recommends setting the following env var on the VPC CNI daemonset:
> ENI_CONFIG_LABEL_DEF=topology.kubernetes.io/zone

Step 5a recommends creating ENIConfigs manually via `kubectl`.

I was hoping to use the Helm chart in this repo to install the ENIConfigs, and otherwise manage upgrades to the VPC CNI add on. However, by default the Helm chart names ENIConfig using the format `REGION` + `USER-SUPPLIED-NAME`. But EKS doesn't put any label on nodes by default that matches this format.

Is this intentional? It feels a little like the Helm chart should produce names that work well with `ENI_CONFIG_LABEL_DEF` (etc) out-of-the-box?

**Environment**:
- Kubernetes version (use `kubectl version`): 1.21
- CNI Version: v1.9.0 (Helm chart 1.1.8)
- OS (e.g: `cat /etc/os-release`): not relevant
- Kernel (e.g. `uname -a`): not relevant

### PR DESCRIPTION
**Pull request by jayanthvn**
**What type of PR is this?**
bug

**Which issue does this PR fix**:
Fixes #1917 

**What does this PR do / Why do we need it**:
Default eniconfig name recommended in EKS docs - https://aws.amazon.com/premiumsupport/knowledge-center/eks-multiple-cidr-ranges/ is AZ name but we used to build the name as region + key(az name) but not annotating the node. Instead we just default it to AZ name and the below label setting will automatically pick the nodes AZ -

```
kubectl set env daemonset aws-node \
    -n kube-system ENI_CONFIG_LABEL_DEF=topology.kubernetes.io/zone
```

**If an issue # is not available please add repro steps and logs from IPAMD/CNI showing the issue**:

**Testing done on this change**:

Yes

```
---
# Source: aws-vpc-cni/templates/eniconfig.yaml
apiVersion: crd.k8s.amazonaws.com/v1alpha1
kind: ENIConfig
metadata:
  name: us-west-2a
spec:
  securityGroups:
    - sg-123
  subnet: subnet-123
---
# Source: aws-vpc-cni/templates/eniconfig.yaml
apiVersion: crd.k8s.amazonaws.com/v1alpha1
kind: ENIConfig
metadata:
  name: us-west-2b
spec:
  securityGroups:
    - sg-456
  subnet: subnet-456
---
```
**Automation added to e2e**:

N/A

**Will this PR introduce any new dependencies?**:

N/A

**Will this break upgrades or downgrades. Has updating a running cluster been tested?**:
N/A

**Does this change require updates to the CNI daemonset config files to work?**:

N/A

**Does this PR introduce any user-facing change?**:

N/A
```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by haouc — APPROVED** [review]
lgtm

**Comment by technotaff-nbs** [comment]
This change has broken our deployment, I think the intention was that you set your naming inside your values file to "a", "b", or "c".

**Comment by joshuastern** [comment]
> This change has broken our deployment, I think the intention was that you set your naming inside your values file to "a", "b", or "c". We have changed our values-file generator now but this was a breaking-change.

We experienced the same issue.

**Comment by jayanthvn** [comment]
Sorry for the inconvenience. This was done to keep the helm chart same as the docs recommendation.

**Pull request merged**
