### PR TITLE
feat(chart): Add support for Prometheus PodMonitor

### PR DESCRIPTION
**Pull request by VLZZZ**
**What type of PR is this?**
feature

**Which issue does this PR fix**:

**What does this PR do / Why do we need it**:
This PR adds support of creating a Promeheus PodMonitor to scrape `/metrics` endpoint of the Pods created by the Daemonset.

**If an issue # is not available please add repro steps and logs from IPAMD/CNI showing the issue**:

**Testing done on this change**:

Example of he installed PodMonitor when `.podMonitor.create: true` in cluster where `.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/PodMonitor"`  
```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: aws-vpc-cni
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2023-10-23T21:42:30Z"
  generation: 1
  labels:
    app.kubernetes.io/name: aws-node
    helm.sh/chart: aws-vpc-cni-1.15.1
    app.kubernetes.io/instance: aws-vpc-cni
    k8s-app: aws-node
    app.kubernetes.io/version: "v1.15.1"
    app.kubernetes.io/managed-by: Helm
  name: aws-node
  namespace: kube-system
  resourceVersion: "1597983189"
  uid: 01913f9d-f786-4ee6-8631-aeac84c1b029
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
    - kube-system
  podMetricsEndpoints:
  - path: /metrics
    port: metrics
    interval: 30s
  selector:
    matchLabels:
      app.kubernetes.io/name: aws-node
      app.kubernetes.io/instance: aws-vpc-cni
```

**Automation added to e2e**:

**Will this PR introduce any new dependencies?**:
Depends on prometheus-operator PodMonitor CRD If ` .podMonitor.create` set to `true`  
Example - https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-operator-crds

**Will this break upgrades or downgrades. Has updating a running cluster been tested?**:
No

**Does this change require updates to the CNI daemonset config files to work?**:
No

**Does this PR introduce any user-facing change?**:

```release-note
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jdn5126** [comment]
@VLZZZ I think this resource is too specialized for us to vend it with the `aws-vpc-cni` chart, especially since we have the CNI Metrics Helper and CloudWatch as the recommended metrics collection solutions. In my mind, something like this belongs in a samples repo

**Comment by VLZZZ** [comment]
@jdn5126 Makes sense, that was my first thought as well, but then I noticed that AWS provides embedded PodMonitor for [aws-node-termination-handler](https://github.com/aws/aws-node-termination-handler/blob/main/config/helm/aws-node-termination-handler/templates/podmonitor.yaml) (my change is based on this example as well).

Of course I'm not insisting on this change to be implemented but it's looks like a good practice to have embedded solution if your code is already capable to provide Prometheus metrics right out of the box.

What are your thoughts on this?
Your concerns related mostly to the fact that PodMonitor is 3rd party extension?

**Comment by jdn5126** [comment]
Yeah, my concern is mostly maintaining this, i.e. making sure it works each release. I do not have very strong opinions here, though, so I will give others a chance to chime in

**Comment by jdn5126** [comment]
@VLZZZ we discussed internally and decided that we do not want to add a 3P integration into the chart to maintain, so I am going to close this, sorry. Customers are free to use `PodMonitor`, but we want to recommend CNI Metrics Helper first

**Pull request closed without merging**
