### PR TITLE
Update golang 1.19.2 EKS-D

### PR DESCRIPTION
**Pull request by jayanthvn**
**What type of PR is this?**
Upgrade golang

**Which issue does this PR fix**:
CVEs with Go before 1.18.6 and 1.19.x before 1.19.1.

**What does this PR do / Why do we need it**:
Upgrade golang

**If an issue # is not available please add repro steps and logs from IPAMD/CNI showing the issue**:
N/A

**Testing done on this change**:

[Will update the tests once executed for ARM and AMD]
**Automation added to e2e**:

Need to run integration tests for ARM and AMD.

**Will this PR introduce any new dependencies?**:

No

**Will this break upgrades or downgrades. Has updating a running cluster been tested?**:
No

**Does this change require updates to the CNI daemonset config files to work?**:

No

**Does this PR introduce any user-facing change?**:

No
```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jayanthvn** [comment]
Have triggered integration tests - https://github.com/aws/amazon-vpc-cni-k8s/actions/runs/3518362106.

Will need both arch tests - AMD and ARM before merge.

**Review by jdn5126 — APPROVED** [review]

**Comment by jayanthvn** [comment]
Integration tests are failing, will try locally before the merge.

**Comment by jayanthvn** [comment]
CNI tests - 

```
=== RUN   TestCNIPodNetworking
Running Suite: CNI Pod Networking Suite - /home/varavaj/github/go_bullseye/amazon-vpc-cni-k8s/test/integration/cni
==================================================================================================================
Random Seed: 1669157529

Will run 15 of 15 specs
Kubeconfig user entry is using deprecated API version client.authentication.k8s.io/v1alpha1. Run 'aws eks update-kubeconfig' to update.
------------------------------
• [SLOW TEST] [150.293 seconds]
[CANARY] test service connectivity when a deployment behind clb service is created clb service pod should be reachable
/home/varavaj/github/go_bullseye/amazon-vpc-cni-k8s/test/integration/cni/service_connectivity_test.go:150
------------------------------
• [SLOW TEST] [142.247 seconds]
[CANARY] test service connectivity when a deployment behind nlb service is created nlb service pod should be reachable
/home/varavaj/github/go_bullseye/amazon-vpc-cni-k8s/test/integration/cni/service_connectivity_test.go:160
------------------------------
• [SLOW TEST] [188.241 seconds]
[CANARY] test service connectivity when a deployment behind cluster IP is created clusterIP service pod should be reachable
/home/varavaj/github/go_bullseye/amazon-vpc-cni-k8s/test/integration/cni/service_connectivity_test.go:168
------------------------------
• [SLOW TEST] [150.365 seconds]
[CANARY] test service connectivity when a deployment behind node port is created node port service pod should be reachable
/home/varavaj/github/go_bullseye/amazon-vpc-cni-k8s/test/integration/cni/service_connectivity_test.go:176
------------------------------
Kubeconfig user entry is using deprecated API version client.authentication.k8s.io/v1alpha1. Run 'aws eks update-kubeconfig' to update.
• [SLOW TEST] [180.635 seconds]
test host networking when pods using IP from primary and secondary ENI are created should have correct host networking setup when running and cleaned up once terminated
/home/varavaj/github/go_bullseye/amazon-vpc-cni-k8s/test/integration/cni/host_networking_test.go:61
------------------------------
• [SLOW TEST] [248.586 seconds]
test host networking when pods using IP from primary and secondary ENI are created Validate Host Networking setup after changing MTU and Veth Prefix
/home/varavaj/github/go_bullseye/amazon-vpc-cni-k8s/test/integration/cni/host_networking_test.go:104
------------------------------
• [SLOW TEST] [88.662 seconds]
test host networking when host networking is tested on invalid input tester pod should error out
/home/varavaj/github/go_bullseye/amazon-vpc-cni-k8s/test/integration/cni/host_networking_test.go:151
------------------------------
• [SLOW TEST] [154.459 seconds]
Test pod networking with prefix delegation enabled when testing TCP traffic between client and server pods should have 99+% success rate
/home/varavaj/github/go_bullseye/amazon-vpc-cni-k8s/test/integration/cni/pod_traffic_test_PD_enabled.go:60
------------------------------
• [SLOW TEST] [124.412 seconds]
Test pod networking with prefix delegation enabled when testing UDP traffic between client and server pods should have 99+% success rate
/home/varavaj/github/go_bullseye/amazon-vpc-cni-k8s/test/integration/cni/pod_traffic_test_PD_enabled.go:72
------------------------------
• [SLOW TEST] [89.853 seconds]
test pod networking when testing ICMP traffic should allow ICMP traffic
/home/varavaj/github/go_bullseye/amazon-vpc-cni-k8s/test/integration/cni/pod_traffic_test.go:183
------------------------------
• [SLOW TEST] [107.927 seconds]
test pod networking [CANARY][SMOKE] when establishing UDP connection from tester to server connection should be established
/home/varavaj/github/go_bullseye/amazon-vpc-cni-k8s/test/integration/cni/pod_traffic_test.go:216
------------------------------
Kubeconfig user entry is using deprecated API version client.authentication.k8s.io/v1alpha1. Run 'aws eks update-kubeconfig' to update.
• [SLOW TEST] [100.050 seconds]
test pod networking [CANARY][SMOKE] when establishing TCP connection from tester to server should allow connection across nodes and across interface types
/home/varavaj/github/go_bullseye/amazon-vpc-cni-k8s/test/integration/cni/pod_traffic_test.go:255
------------------------------
• [SLOW TEST] [126.363 seconds]
aws-node env test aws-node environment variable AWS_VPC_K8S_CNI_LOG_FILE test
/home/varavaj/github/go_bullseye/amazon-vpc-cni-k8s/test/integration/cni/vpc_cni_logfile_test.go:65
------------------------------
• [SLOW TEST] [72.331 seconds]
Test pod networking with prefix delegation enabled <-> disabled when testing TCP traffic between client and server pods on enabling PD should have 99+% success rate
/home/varavaj/github/go_bullseye/amazon-vpc-cni-k8s/test/integration/cni/pod_traffic_test_PD_toggle.go:75
------------------------------
• [SLOW TEST] [172.468 seconds]
Test pod networking with prefix delegation enabled <-> disabled when testing TCP traffic between client and server pods on disabling PD should have 99+% success rate
/home/varavaj/github/go_bullseye/amazon-vpc-cni-k8s/test/integration/cni/pod_traffic_test_PD_toggle.go:104
------------------------------

Ran 15 of 15 Specs in 2229.809 seconds
SUCCESS! -- 15 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestCNIPodNetworking (2229.81s)
PASS

Ginkgo ran 1 suite in 38m7.703186091s
Test Suite Passed
```

**Comment by jayanthvn** [comment]
Flaky test focused run -

```
• [SLOW TEST] [220.236 seconds]
[CANARY][SMOKE] ENI/IP Leak Test ENI/IP Released on Pod Deletion Verify that on Pod Deletion, ENI/IP State is restored
/home/varavaj/github/go_bullseye/amazon-vpc-cni-k8s/test/integration/ipamd/eni_ip_leak_test.go:26
------------------------------
SSSSSSSSS

Ran 1 of 26 Specs in 311.897 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 25 Skipped
PASS | FOCUSED
```

**Pull request merged**
