### PR TITLE
scripts/lib: use tester v0.8.5

### PR DESCRIPTION
**Pull request by gyuho**
~Worker nodes logs aren't used for now, so disable.~

https://github.com/aws/aws-k8s-tester/blob/master/CHANGELOG-0.8.md

### CODE REVIEW

**Comment by jaypipes** [comment]
@gyuho what do you mean by "worker nodes aren't used for now"? The MNG's worker nodes are indeed used to house Pods that are spun up in the integration tests...

**Comment by gyuho** [comment]
@jaypipes Meant to say worker nodes "logs" :)

**Comment by SaranBalaji90** [comment]
@gyuho worker nodes logs are useful while investigating failures. What's the harm in uploading these logs? Do we pay for these extra spaces somewhere?

**Comment by gyuho** [comment]
@SaranBalaji90 Currently, the tester tool only downloads to the local machine. Uploading config file and kubeconfig to S3 bucket is supported but upload all logging files aren't "yet". I can implement this feature in the next release.

**Comment by gyuho** [comment]
Updated upstream to upload gzipped file

> {"level":"info","ts":"2020-03-19T11:50:50.525-0700","caller":"mng/logs.go:464","msg":"wrote log files","instance-id":"i-07bd14ea952b037ea","files":133,"total-downloaded-files":133}
{"level":"info","ts":"2020-03-19T11:50:50.526-0700","caller":"mng/logs.go:471","msg":"wrote all log files","log-dir":"/tmp/leegyuho-test-prod-logs-mngs","total-downloaded-files":133}
{"level":"info","ts":"2020-03-19T11:50:50.531-0700","caller":"mng/logs.go:68","msg":"gzipping logs dir","logs-dir":"/tmp/leegyuho-test-prod-logs-mngs","file-path":"/tmp/leegyuho-test-prod-mng-logs.tar.gz"}
{"level":"info","ts":"2020-03-19T11:50:50.577-0700","caller":"mng/logs.go:74","msg":"gzipped logs dir","logs-dir":"/tmp/leegyuho-test-prod-logs-mngs","file-path":"/tmp/leegyuho-test-prod-mng-logs.tar.gz"}
{"level":"info","ts":"2020-03-19T11:50:51.403-0700","caller":"mng/logs.go:99","msg":"uploaded the gzipped file","bucket":"aws-k8s-tester-eks-s3-bucket","remote-path":"leegyuho-test-prod/leegyuho-test-prod-mng-logs.tar.gz"}

Will release a new one.

**Comment by gyuho** [comment]
@jaypipes @SaranBalaji90 Released a new one 
https://github.com/aws/aws-k8s-tester/blob/master/CHANGELOG-0.8.md.

Now uploads gzipped log files to S3 bucket.

**Comment by mogren** [comment]
> @jaypipes @SaranBalaji90 Released a new one
> https://github.com/aws/aws-k8s-tester/blob/master/CHANGELOG-0.8.md.
> 
> Now uploads gzipped log files to S3 bucket.

Nice! Running the tests now

**Comment by SaranBalaji90** [comment]
@gyuho what I meant to ask is, do we still upload kubelet logs? that's super useful for investigation.

**Comment by gyuho** [comment]
@SaranBalaji90 Yes. e.g. `i-00a1505dc938f9296-kubelet.service.out.log` is the kubelet logs from the instance `i-00a1505dc938f9296`

**Pull request merged**
