### PR TITLE
Add error messages in aws-k8s-agent initialization

### PR DESCRIPTION
**Pull request by ryan-joynbio**
**What type of PR is this?**

Feature: Usability

**Which issue does this PR fix**:

N/A

**What does this PR do / Why do we need it**:

Right now if there is an error from any one of these methods, the error never gets presented to the user and debugging is impossible.

**If an issue # is not available please add repro steps and logs from IPAMD/CNI showing the issue**:

N/A

**Testing done on this change**:

N/A

**Automation added to e2e**:

N/A

**Will this break upgrades or downgrades. Has updating a running cluster been tested?**:

No. No.

**Does this change require updates to the CNI daemonset config files to work?**:

No.

**Does this PR introduce any user-facing change?**:

No.

```release-note
Adds error messages during aws-k8s-agent initilization
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jayanthvn** [comment]
Thanks for opening this PR. Just few minor nits.

**Comment by ryan-joynbio** [comment]
@jayanthvn Updated!! Thank you!!

**Review by Shreya027 — APPROVED** [review]

**Comment by jayanthvn** [comment]
@ryan-joynbio - Sorry for the delay, can you please update your branch?

**Comment by ryan-joynbio** [comment]
@jayanthvn 🙏 ty, updated!!

**Review by jayanthvn — APPROVED** [review]

**Pull request merged**
