### PR TITLE
Added envFrom field for both image and init image

### PR DESCRIPTION
**Pull request by giordanocardillo**
**What type of PR is this?**

feature

**Which issue does this PR fix**:

**What does this PR do / Why do we need it**:

It adds the ability to use envFrom fields to configure env reading eg. a configmap 

**If an issue # is not available please add repro steps and logs from IPAMD/CNI showing the issue**:

**Testing done on this change**:

Template generated successfully using helm

**Automation added to e2e**:

**Will this PR introduce any new dependencies?**:

**Will this break upgrades or downgrades. Has updating a running cluster been tested?**:

**Does this change require updates to the CNI daemonset config files to work?**:

**Does this PR introduce any user-facing change?**:

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jdn5126** [comment]
@giordanocardillo there is an open issue to use a ConfigMap for VPC CNI: https://github.com/aws/amazon-vpc-cni-k8s/issues/2102 , but it is not something currently on our roadmap. There are other implications of allowing ConfigMaps for config, so this is something we will have to hold off on

**Comment by jayanthvn** [comment]
@giordanocardillo - Just curious to know, are you using config maps in your cluster? if so how are you triggering aws-node restarts when there is a change in CM.

**Comment by giordanocardillo** [comment]
My company is using this to pass http_proxy, no_proxy variables that are unified between various environments

**Comment by jdn5126** [comment]
Closing this PR as we are not ready to introduce ConfigMaps here

**Pull request closed without merging**
