### PR TITLE
1277 show eni attachment in node status

### PR DESCRIPTION
**Pull request by vissree**
**What type of PR is this?**
feature

**Which issue does this PR fix**: https://github.com/aws/amazon-vpc-cni-k8s/issues/1277

**What does this PR do / Why do we need it**:
A node event is sent, together with the ENI id when an ENI is allocated or free'd. This will helps to have a historic data of the ENIs that were attached to and detached from the node when audit logs are enabled.

**If an issue # is not available please add repro steps and logs from IPAMD/CNI showing the issue**:

**Testing done on this change**:
$ kubectl describe node ip-192-168-122-240.ap-southeast-1.compute.internal
Name:               ip-192-168-122-240.ap-southeast-1.compute.internal
--- truncated ---
Events:
  Type    Reason                   Age                From        Message
  Normal  Starting                 78s                kubelet     Starting kubelet.
  Normal  NodeHasSufficientMemory  77s (x2 over 77s)  kubelet     Node ip-192-168-122-240.ap-southeast-1.compute.internal status is now: NodeHasSufficientMemory
  Normal  NodeHasNoDiskPressure    77s (x2 over 77s)  kubelet     Node ip-192-168-122-240.ap-southeast-1.compute.internal status is now: NodeHasNoDiskPressure
  Normal  NodeHasSufficientPID     77s (x2 over 77s)  kubelet     Node ip-192-168-122-240.ap-southeast-1.compute.internal status is now: NodeHasSufficientPID
  Normal  NodeAllocatableEnforced  77s                kubelet     Updated Node Allocatable limit across pods
  Normal  Starting                 63s                kube-proxy  Starting kube-proxy.
  Normal  NodeReady                15s                kubelet     Node ip-192-168-122-240.ap-southeast-1.compute.internal status is now: NodeReady
  Normal  AllocatedENI             8s                 ipamd       Allocated ENI eni-0817b60e20f1058dc

**Automation added to e2e**:

**Will this break upgrades or downgrades. Has updating a running cluster been tested?**:
Tested upgrading the cluster.

**Does this change require updates to the CNI daemonset config files to work?**:

**Does this PR introduce any user-facing change?**:

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jayanthvn** [comment]
@vissree - Sorry for the delay with review. Can you please fix the conflicts?

**Comment by vissree** [comment]
> @vissree - Sorry for the delay with review. Can you please fix the conflicts?

No problem @jayanthvn, Happy New Year!
I have fixed the merge conflicts and running the unit tests once. Will push the changes as soon as it's done.

**Comment by jayanthvn** [comment]
@vissree - We are working on changes to add pod and node events so is it fine if we can close this PR and I will pull in your changes as part of the new PR?

**Comment by vissree** [comment]
@jayanthvn Sure, that sounds good 👍

**Comment by jayanthvn** [comment]
> @jayanthvn Sure, that sounds good 👍

Thank you :)

**Comment by jdn5126** [comment]
Closing PR as #1277 will be addressed using event recorder framework added in https://github.com/aws/amazon-vpc-cni-k8s/pull/1536 . #1277 is assigned to @sushrk

**Pull request closed without merging**
