### PR TITLE
Restructure existing code to work with latest version of operator-sdk

### PR DESCRIPTION
**Pull request by adammw**
**WORK IN PROGRESS**

*Issue #:* #522

*Description of changes:* Restructure existing code to work with latest version of operator-sdk. 

Following the recommendation of the [operator-sdk migration guide](https://github.com/operator-framework/operator-sdk/blob/master/doc/migration/v0.1.0-migration-guide.md), I created a new operator-sdk project and copied as much of the existing code as possible. Most changes are around the controller logic, as the operator-sdk API has changed from combined Handle() methods which take change events, to Reconcile() which take reconciliation requests of a single object instead.

*Open Questions*
- Will this code be accepted for a new minor release?
- Should the log code be left alone with the built-in seelog-based utilities or migrated to `sigs.k8s.io/controller-runtime/pkg/log`

*TODO*
- [x] Fix/update tests
- [ ] Set correct log-levels to reduce log spam
- [ ] Increase reconciliation period, 5 seconds seems awfully low

---

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by mogren** [comment]
@adammw Hey, thanks for working on this. We would definitely consider this PR for a new minor release, after enough testing of course. Probably not for v1.6.0, since we are aiming to get that version out pretty soon.

That said, this is a pretty big change. I did take a quick stab at doing the smallest possible change required to update, but that was still a lot of work and didn't really follow the standard pattern used by the operator-framework.

**Comment by adammw** [comment]
Yeah, I think apart from the logging changes, this is essentially the
smallest change as operator sdk API change necessitates splitting up the
existing eniconfig controller into two.

That being said, the actual value of using controllers in the first place
seems to be reasonably low since the ipam module polls the controllers for
information periodically, meaning it doesn't directly get notified of
changes and they're only applied for new ipam requests.

**Comment by adammw** [comment]
Another question is how far away the rearchitecture discussed on the
roadmap is away, whether this makes sense to merge in a minor version, or
wait and skip to the new codebase when it's ready.

**Comment by jaypipes** [comment]
@adammw sorry the delay in getting back to you on this! Are you still interested in working on this? There's been quite a few changes since this PR was originally submitted and you'd need to rebase (or likely restart afresh). The 2.x series CNI plugin won't be out until at the earliest next year and we'll still be supporting the 1.x plugin series for years to come, so I think this is still important tech debt to work on.

**Comment by mogren** [comment]
The last update of this PR was over a year ago, closing it.

**Pull request closed without merging**
