### PR TITLE
add support for running canary script in different regions

### PR DESCRIPTION
**Pull request by abhipth**
**What type of PR is this?**
Add region support for the canary script.

**Which issue does this PR fix**:

**What does this PR do / Why do we need it**:

**If an issue # is not available please add repro steps and logs from IPAMD/CNI showing the issue**:

**Testing done on this change**:

**Automation added to e2e**:

**Will this break upgrades or downgrades. Has updating a running cluster been tested?**:

**Does this change require updates to the CNI daemonset config files to work?**:

**Does this PR introduce any user-facing change?**:

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by vikasmb — APPROVED** [review]
lgtm

**Review by orsenthil — APPROVED** [review]
Is there a possiblity to refactor these scripts (in future) so that repetition with this https://github.com/abhipth/amazon-vpc-resource-controller-k8s/blob/d2876abf229695a0be7cd10194f7f3d9f6b23efa/scripts/test/run-canary-test.sh could be avoided?

**Comment by abhipth** [comment]
Yeah that's a good idea. The add-on installation code is duplicate in both places, I am not sure of a way to import scripts across different repos easily. We can possibly do this operation in Go and have a central framework used by all networking repositories. This will also get rid of duplication we have in our testing framework also.

**Comment by orsenthil** [comment]
> I am not sure of a way to import scripts across different repos easily.

Oh. I failed to note the repo difference. I thought, it was only a directory difference.

Usually, the way is keep a separate utils folder for common tasks across repos.

a. Either use git submodule
b. Or hard-code dependency, and clone it before repo specific thing is called.

The current repetition is fine too! ( I didn't notice that they were two difference repos).

**Pull request merged**
