### PR TITLE
Added exists check for cni pods

### PR DESCRIPTION
**Pull request by Zyqsempai**
issue #592 

Added check if cniPod still exists and not terminated

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by Zyqsempai** [comment]
@mogren PTAL, I know that it's not so efficient but I didn't found more elegant way to do that.

**Comment by shyamjvs** [comment]
I don't think #592 is a issue - replied there. This change doesn't seem to offer much given that we're already updating `d.cniPods` inside `handlePodUpdate`.

@Zyqsempai Let me know if I'm missing sth.

**Comment by mogren** [comment]
Like @shyamjvs said, `delete(d.cniPods, key)` is already called on any pod event in `handlePodUpdate()` so I don't think this change would help.

**Comment by jaypipes** [comment]
@Zyqsempai see comments from @shyamjvs and @mogren. Closing this pull request out.

**Pull request closed without merging**
