### PR TITLE
Use GetNodes in metrics-helper; explicitly install latest addon

### PR DESCRIPTION
**Pull request by jdn5126**
**What type of PR is this?**
cleanup

**Which issue does this PR fix**:
N/A

**What does this PR do / Why do we need it**:
This PR updates metrics-helper and e2e/snat integration tests to get nodes to test against from the set matching the given node group name/value.

This PR also updates `update-cni-image.sh` script to install latest CNI image from manifest by default. The goal is for integration test callers to run this script before running the test, as it adds flexibility to the chosen image.

**If an issue # is not available please add repro steps and logs from IPAMD/CNI showing the issue**:
N/A

**Testing done on this change**:
Manually verified integration test scripts pass.

**Automation added to e2e**:
N/A

**Will this PR introduce any new dependencies?**:
No

**Will this break upgrades or downgrades. Has updating a running cluster been tested?**:
No

**Does this change require updates to the CNI daemonset config files to work?**:
No

**Does this PR introduce any user-facing change?**:
No

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by orsenthil — APPROVED** [review]
LGTM.

**Comment by orsenthil** [comment]
Please fix `make: *** [Makefile:300: format] Error 12`

**Comment by jdn5126** [comment]
> Please fix `make: *** [Makefile:300: format] Error 12`

`make check-format` would not pass until `make format` was executed, which fixed comment strings. All changes in additional files are just spaces in comments.

**Review by M00nF1sh — DISMISSED** [review]
/lgtm

**Review by jayanthvn — APPROVED** [review]
lgtm

**Review by sushrk — APPROVED** [review]
LGTM.

**Pull request merged**
