### PR TITLE
Update Calico version to v3.8.1

### PR DESCRIPTION
**Pull request by lmm**
*Description of changes:*

* Update Calico image tags from `v3.3.6` to `v3.8.1`
* Add required RBAC changes and CRDs for `v3.8.1`
* Remove deprecated apiVersions and fields.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by lmm** [comment]
I notice now that some of changes I've made are also in https://github.com/aws/amazon-vpc-cni-k8s/pull/504

**Comment by mogren** [comment]
Hey @lmm, thanks a lot. I'll take a look at this before making a v1.6.0 release

**Comment by tmjd** [comment]
@mogren WDYT about making these changes for 1.5.2 also (which I see an RC is up for)?
When would they need to be submitted by?

**Comment by mogren** [comment]
@tmjd Hey, sorry, already cut the v1.5.2 release. Will try to get v1.6.0 out before the end of this month.

**Comment by nickdgriffin** [comment]
This is still listed as being in the 1.5.3 release, but that doesn't seem to be the case for the upgrade to v3.8.1 which looks to have been pushed to 1.6.0.

**Comment by mogren** [comment]
@nickdgriffin Hey, thanks for catching this, I'll update the configs.

**Comment by nickdgriffin** [comment]
@mogren No problem, was just reviewing what I needed for an upgrade and noticed the discrepancy - thanks for sorting!

**Comment by nickdgriffin** [comment]
@mogren I think it's needed on the 1.5.4 branch too, as that's missing it. This also means that anyone that uses the tag (like I did) to get the appropriate version will still get the old one unless they are remade.

**Comment by mogren** [comment]
@nickdgriffin I had it locally, forgot to push. Thanks for the reminder!

**Pull request merged**
