### PR TITLE
Preparation for v1.12.4 release

### PR DESCRIPTION
**Pull request by jdn5126**
**What type of PR is this?**
release preparation

**Which issue does this PR fix**:
N/A

**What does this PR do / Why do we need it**:
This PR updates `CHANGELOG.md`, helm charts, and `config/master` manifests in preparation for v1.12.4 release. Note that there is no `v1.12.3` release. This is because `v1.12.3` had to be skipped due to tagging issues.

**If an issue # is not available please add repro steps and logs from IPAMD/CNI showing the issue**:
N/A

**Testing done on this change**:
N/A

**Automation added to e2e**:
N/A

**Will this PR introduce any new dependencies?**:
No

**Will this break upgrades or downgrades. Has updating a running cluster been tested?**:
N/A

**Does this change require updates to the CNI daemonset config files to work?**:
No

**Does this PR introduce any user-facing change?**:
No

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by orsenthil — DISMISSED** [review]
LGTM.

**Review by jayanthvn — DISMISSED** [review]

**Comment by orsenthil** [comment]
Hi @jdn5126 - Let's hold on with publishing this yet. Perhaps we might need to build with Go 1.19.6 - https://groups.google.com/g/golang-announce/c/V0aBFqaFs_E/m/CnYKgKwBBQAJ?utm_medium=email&utm_source=footer  cc: @jayanthvn

**Comment by jdn5126** [comment]
> Hi @jdn5126 - Let's hold on with publishing this yet. Perhaps we might need to build with Go 1.19.6 - https://groups.google.com/g/golang-announce/c/V0aBFqaFs_E/m/CnYKgKwBBQAJ?utm_medium=email&utm_source=footer cc: @jayanthvn

This is resolved now

**Review by jaydeokar — APPROVED** [review]
LGTM

**Pull request merged**
