### PR TITLE
Manifest Updates

### PR DESCRIPTION
**Pull request by achevuru**
**What type of PR is this?**
Enhancement

**Which issue does this PR fix**:
Increase liveness/readiness probe timeout values.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by M00nF1sh — APPROVED** [review]
/lgtm

**Review by sramabad1 — APPROVED** [review]
LGTM

**Review by jayanthvn — CHANGES_REQUESTED** [review]
Can we update the charts folder? - https://github.com/aws/amazon-vpc-cni-k8s/blob/release-1.10/charts/aws-vpc-cni/values.yaml#L95

**Comment by jayanthvn** [comment]
Lgtm but do we need charts version upgrade?

**Review by jayanthvn — APPROVED** [review]

**Pull request merged**
