### PR TITLE
vendor: dep cleanup

### PR DESCRIPTION
**Pull request by adnxn**
* added dep prune targets for `go-tests` and `unused-packages`
* removed sirupsen/logrus dependency since not used in any import statements
* ran dep ensure

```
% make unit-test | grep ok
ok  	github.com/aws/amazon-vpc-cni-k8s/pkg/awsutils	31.032s	coverage: 78.9% of statements
ok  	github.com/aws/amazon-vpc-cni-k8s/plugins/routed-eni	1.018s	coverage: 70.3% of statements
ok  	github.com/aws/amazon-vpc-cni-k8s/plugins/routed-eni/driver	1.014s	coverage: 76.3% of statements
ok  	github.com/aws/amazon-vpc-cni-k8s/plugins/routed-eni/driver	1.014s
ok  	github.com/aws/amazon-vpc-cni-k8s/pkg/k8sapi	1.441s	coverage: 81.5% of statements
ok  	github.com/aws/amazon-vpc-cni-k8s/pkg/networkutils	1.010s	coverage: 38.0% of statements
ok  	github.com/aws/amazon-vpc-cni-k8s/ipamd	1.439s	coverage: 29.4% of statements
ok  	github.com/aws/amazon-vpc-cni-k8s/ipamd/datastore	1.441s	coverage: 95.8% of statements
```

### CODE REVIEW

**Comment by liwenwu-amazon** [comment]
@adnxn Thanks for the PR. Shall we merge this with PR #32 ?

**Comment by adnxn** [comment]
@liwenwu-amazon sounds good. let me know if you need me to make any changes.

**Comment by liwenwu-amazon** [comment]
@adnxn Great if you can take over PR#32 and merge this change.  Thanks again.

**Comment by liwenwu-amazon** [comment]
use #77 for master branch

**Pull request closed without merging**
