### PR TITLE
1.10.2 changes

### PR DESCRIPTION
**Pull request by cgchinmay**
**What type of PR is this?**
feature

**Which issue does this PR fix**:
Changes for v1.10.2 

**What does this PR do / Why do we need it**:
cherry picking these 6 changes for v1.10.2 release (already merged to master)
https://github.com/aws/amazon-vpc-cni-k8s/pull/1773 - ipamd error code fix
https://github.com/aws/amazon-vpc-cni-k8s/pull/1715 - cni metrics helper change
https://github.com/aws/amazon-vpc-cni-k8s/pull/1705 - vlanId changes
https://github.com/aws/amazon-vpc-cni-k8s/pull/1823 - disable network provisioning condition fix
https://github.com/aws/amazon-vpc-cni-k8s/pull/1832 - go version updated to 1.17
https://github.com/aws/amazon-vpc-cni-k8s/pull/1804 - use public ecr for AL2
https://github.com/aws/amazon-vpc-cni-k8s/pull/1776 - auto sync manifest changes 
https://github.com/aws/amazon-vpc-cni-k8s/pull/1818 - remove sudo from workflow files for docker prune
https://github.com/aws/amazon-vpc-cni-k8s/pull/1802 - remove set -x from bash, add -Ss to curl

**Testing done on this change**:

yes

**Will this break upgrades or downgrades. Has updating a running cluster been tested?**:
It shouldn't affect. Tried following upgrade/downgrade tests 
for x : range(v1.7.5: v1.10.1)
  - Create pod with x and delete with v1.10.2
  - Create pod with v1.10.2 and delete with x 

Will add this to ginkgo 

**Does this change require updates to the CNI daemonset config files to work?**:

yes

**Does this PR introduce any user-facing change?**:

No

** Will this PR introduce any new dependencies?**:
Requires CNI spec 0.4.0

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jayanthvn — APPROVED** [review]
lgtm

**Review by jayanthvn — APPROVED** [review]

**Comment by vikasmb** [comment]
@cgchinmay could you please cherrypick this change https://github.com/aws/amazon-vpc-cni-k8s/pull/1818 to release 1.10 in this PR ? It would be needed for the integ tests to pass.

**Comment by vikasmb** [comment]
Regarding inclusion of '.github/workflows/weekly-cron-test.yml', wouldn't cron based workflow trigger in master/main branches only ? https://github.community/t/scheduled-builds-of-non-default-branch/16306/21

**Comment by cgchinmay** [comment]
> Regarding inclusion of '.github/workflows/weekly-cron-test.yml', wouldn't cron based workflow trigger in master/main branches only ? https://github.community/t/scheduled-builds-of-non-default-branch/16306/21

I think we can remove it . It got added with cherry-picket commit

**Comment by chlunde** [comment]
@cgchinmay I think it is possible to improve the changelog a bit, it's difficult to relate to the changes from a consumer perspective. For example, maybe the VLAN change should mention statefulset. Maybe something along the lines of "Fix an issue with for securitygroups per pod where statefulset did not get working network" would be better than "Add VlanId in the cmdAdd Result struct"

**Comment by cgchinmay** [comment]
> @cgchinmay I think it is possible to improve the changelog a bit, it's difficult to relate to the changes from a consumer perspective. For example, maybe the VLAN change should mention statefulset. Maybe something along the lines of "Fix an issue with for securitygroups per pod where statefulset did not get working network" would be better than "Add VlanId in the cmdAdd Result struct"

Thanks for the feedback. I have updated the changelog to explicitly call out the Issue with security group for pods.

**Pull request merged**
