### PR TITLE
Update go.mod for integration folder

### PR DESCRIPTION
**Pull request by vikasmb**
- Update go.mod for integration folder

**What type of PR is this?**
Cleanup

**Which issue does this PR fix**:
Updates K8s dependencies in integration folder. Used https://github.com/kubernetes/kubernetes/issues/79384#issuecomment-521493597 to obtain the new versions.

**What does this PR do / Why do we need it**:
Updates K8s dependencies in integration folder 

**If an issue # is not available please add repro steps and logs from IPAMD/CNI showing the issue**:

**Testing done on this change**:

**Automation added to e2e**:

**Will this break upgrades or downgrades. Has updating a running cluster been tested?**:
No

**Does this change require updates to the CNI daemonset config files to work?**:

No
**Does this PR introduce any user-facing change?**:

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by vikasmb** [comment]
Integration test execution has the following error for this change:
```
go: k8s.io/api@v0.21.5 requires
	github.com/stretchr/testify@v1.6.1 requires
	gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c: invalid version: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /home/ssm-user/go/pkg/mod/cache/vcs/0901dc1ef67fcce1c9b3ae51078740de4a0e2dc673e720584ac302973af82f36: exit status 128:
	fatal: unable to access 'https://gopkg.in/yaml.v3/': SSL certificate problem: certificate has expired
	```
	Will check this and update the PR.

**Comment by orsenthil** [comment]
This looks good to me. The ARM images are failure seems like a disk issue. It can be re-run to make sure valid artifacts can be built.

**Review by orsenthil — APPROVED** [review]
LGTM.

**Comment by vikasmb** [comment]
> This looks good to me. The ARM images are failure seems like a disk issue. It can be re-run to make sure valid artifacts can be built.

ARM build is successful now.

**Review by jayanthvn — APPROVED** [review]
lgtm

**Pull request merged**
