### PR TITLE
Link changelog references

### PR DESCRIPTION
**Pull request by praveenperera**
**What type of PR is this?**

 * cleanup

Links all GitHub profiles of contributors in the CHANGELOG.md

### CODE REVIEW

**Review by jayanthvn — APPROVED** [review]
Looks good. Thanks for taking care of this.

**Comment by jayanthvn** [comment]
Can you please update the branch?

**Comment by praveenperera** [comment]
hey @jayanthvn, I did a merge, do you want me to do a rebase and force push instead?

**Comment by jayanthvn** [comment]
I was able to squash and merge. Thank you!

**Pull request merged**
