### PR TITLE
update list of instances to be more metal \m/

### PR DESCRIPTION
**Pull request by pdbogen**
*Issue #, if available:* n/a

*Description of changes:* add missing `metal` instances, data from https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html#AvailableIpPerENI

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by pdbogen** [comment]
n.b., the CI failures look spurious / network-related, don't seem to be a result of this change.

**Comment by mogren** [comment]
@pdbogen Yes, TravisCI seem to have timeout issues the last few days. 

Also, #528 is basically exactly the same PR as this one, except that you fixed the `i3.metal` IP count as well.

**Comment by pdbogen** [comment]
ah! I didn't think to check for an existing PR. In response to the query on _that_ one, we haven't tested on a `.metal` instance yet, but I think we plan to in the next few days.

**Comment by pdbogen** [comment]
Ya. And to close the loop, we've tested on some `metal` instances and it's working well.

**Pull request merged**
