### PR TITLE
Updated go version in go.mod

### PR DESCRIPTION
**Pull request by cgchinmay**
**What type of PR is this?**
feature

**Which issue does this PR fix**:
Update go version

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jayanthvn** [comment]
Even arm and x86 builds look fine.

**Review by jayanthvn — APPROVED** [review]

**Review by orsenthil — APPROVED** [review]
I had a question if the upgrade golang, will need any integration testing before release.

I think,  Integration testing will be safe, since we are upgrading go.mod dependencies along with the runtime.

**Comment by jayanthvn** [comment]
Yeah agreed. We would need to run the integration test suite before release.

**Comment by cgchinmay** [comment]
> I had a question if the upgrade golang, will need any integration testing before release.
> 
> I think, Integration testing will be safe, since we are upgrading go.mod dependencies along with the runtime.

Integration and e2e tests did pass

**Comment by orsenthil** [comment]
> Integration and e2e tests did pass

Nice. You could link to the success of the Integration test link in the SIM tickets, just for future reference.
VPC resource controller integration tests could be included too.

Thank you, @cgchinmay

**Pull request merged**
