### PR TITLE
Update yaml.v3 package dependency

### PR DESCRIPTION
**Pull request by vikasmb**
**What type of PR is this?**

cleanup
**Which issue does this PR fix**:
Upgrades dependency yaml.v3 package to 3.0.1 version

**What does this PR do / Why do we need it**:
Upgrades yaml.v3 package to 3.0.1 version

**If an issue # is not available please add repro steps and logs from IPAMD/CNI showing the issue**:

**Testing done on this change**:

**Automation added to e2e**:

**Will this PR introduce any new dependencies?**:

**Will this break upgrades or downgrades. Has updating a running cluster been tested?**:
No

**Does this change require updates to the CNI daemonset config files to work?**:

No
**Does this PR introduce any user-facing change?**:

No
```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by orsenthil — APPROVED** [review]
LGTM.

**Review by jayanthvn — APPROVED** [review]
lgtm, lets build the images and run IT internally.

**Comment by vikasmb** [comment]
Integ test for this change has passed in https://github.com/aws/amazon-vpc-cni-k8s/runs/7461543551?check_suite_focus=true

**Review by orsenthil — APPROVED** [review]
LGTM.

**Pull request merged**
