### PR TITLE
Update VPC ENI/IP limits table to add r5, r5d, z1d and t3 instance types

### PR DESCRIPTION
**Pull request by cablespaghetti**
*Description of changes:*
Add new instances types so users of them don't get messages such as `[ERROR] Failed to get eni limit due to unknown instance type r5.large` and a failure to assign any interfaces to pods.

### CODE REVIEW

**Comment by vsiddharth** [comment]
@cablespaghetti Thanks a lot for submitting this pull-request. Your changes look good to me. 

However, could you please confirm that this contribution is made under the terms of the Apache 2.0 license?

Additionally, could you also describe any tests that you performed to validate the changes??

**Comment by cablespaghetti** [comment]
@vsiddharth Sure. My contribution is made under the Apache 2.0 license.

I have not been able to get a working build environment unfortunately, so have not been able to test my changes. However I have very carefully checked them against https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html#AvailableIpPerENI

Thanks

**Comment by doxavore** [comment]
I can confirm when taking a broken system using t3.medium instances to t2.medium, this is fixed. It does appear that until a new version is released (and perhaps the aws-ami picks it up) this is still a problem.

**Comment by Jeeppler** [comment]
I was able to successfully use a t3.large in my EKS cluster.

**Comment by msvechla** [comment]
@Jeeppler what AMI did you use?

**Comment by Jeeppler** [comment]
@msvechla 

I used the [Terraform AWS EKS](https://github.com/terraform-aws-modules/terraform-aws-eks/) module. The image is calculated by using the following snippet:

source: [terraform-aws-eks/data.tf](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/data.tf#L18)

```
data "aws_ami" "eks_worker" {
  filter {
    name   = "name"
    values = ["amazon-eks-node-*"]
  }

  most_recent = true
  owners      = ["602401143452"] # Amazon
}

**Comment by msvechla** [comment]
@Jeeppler perfect, we are using the same. Then re-running terraform and terminating the running instances should fix the issue. Thanks!

**Comment by Jeeppler** [comment]
@msvechla yes. I created a cluster from scratch. I did not try to change the instance type in a already existing cluster.

**Pull request merged**
