### PR TITLE
Bump Calico to v3.13.0

### PR DESCRIPTION
**Pull request by lmm**
*Issue #, if available:*
Related to aws/eks-charts#71

*Description of changes:*
This bumps Calico to v3.13.0, building off of https://github.com/aws/amazon-vpc-cni-k8s/pull/838

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by mogren** [comment]
Thanks a lot for the updates @lmm! It all looks good, but I'll test it some as soon as I'm back in the office.

**Comment by lmm** [comment]
Actually, if we can wait a few days or so, a new Calico version should be coming

**Comment by mogren** [comment]
@lmm Sure, sounds good to me :)

**Comment by ricardochimal** [comment]
:wave: calico v3.13 was release last week, do you plan on updating this branch or should I create a new one for review?

**Comment by mogren** [comment]
@ricardochimal I think that was what @lmm was referring to earlier. We can bump it in this branch.

**Comment by ricardochimal** [comment]
@lmm thanks! I'll test this out on my setup as well today

**Comment by lmm** [comment]
Thanks @ricardochimal !

**Comment by ricardochimal** [comment]
thanks again for this

**Pull request merged**
