### PR TITLE
update calico version and add v3.3 required changes

### PR DESCRIPTION
**Pull request by 2ffs2nns**
Rev calico to v3.3.1

# validation
* Fresh EKS cluster install w/calico-v3.3.1 completes w/out errors
* Guestbook-app demo completes w/out errors
* Stars-demo completes w/out errors
* Kubernetes e2e run w/NetworkPolicy focus passes w/out failures/errors
* Rolling upgrade EKS cluster w/calico-3.1.3 to calico-3.3.1 completes w/out errors

### CODE REVIEW

**Comment by caseydavenport** [comment]
LGTM

**Comment by garo** [comment]
Is there a reason why this has not been merged? I'm interested to upgrade to calico 3.3.1, but I'm not sure how well that is supported with EKS.

**Comment by mogren** [comment]
I think this was just missed earlier, and I don't know Calico well enough to completely understand this change, but @caseydavenport saying it's good is encouraging.

That said, the PR needs to be updated to add the same changes to `config/v1.3/calico.yaml`.

**Comment by caseydavenport** [comment]
At this point we may want to consider updating the PR to use something a bit more modern than v3.3.1!

v3.3.4 is out, so we should at least use that, and then maybe do a separate PR afterwards to do a minor bump - I'd guess it's better to not block this PR on testing with v3.5.

@2ffs2nns WDYT?

**Comment by 2ffs2nns** [comment]
yeah, let me update this to v3.3.4, make the change to `config/v1.3/calico.yaml` per @mogren then add another PR so I can run through some tests with v3.5.2 @caseydavenport

**Comment by mogren** [comment]
II guess we would like to have this fix in the next version: https://github.com/projectcalico/libcalico-go/pull/1040

**Comment by garo** [comment]
@mogren Based on my testing the current quay.io/calico/node:release-v3.1 nor the very new quay.io/calico/node:v3.1.6 did not fix the issue https://github.com/projectcalico/felix/issues/1966

To help Tigera to triage this bug I think it would be appropriate to update EKS recommendation to run Calico v3.3 (ie merge this PR) so that they don't need to worry about debugging this with the 3.1 release, which is already unsupported.

**Comment by garo** [comment]
Just to confirm: the release-v3.1 has fixed https://github.com/projectcalico/libcalico-go/pull/1040 so I presume the release-v3.3 has this also fixed.

**Comment by mogren** [comment]
@garo Yes, that is correct. Hopefully Eric will have some time soon, since he knows Calico way better than me.

**Comment by tiffanyfay** [comment]
Hey, @2ffs2nns @caseydavenport, how are things going with this? Thanks.

**Comment by 2ffs2nns** [comment]
I'm not sure if I'll be able to get to this this week. Let me put this on
the plan for our next sprint, starting Monday 25th

Eric

*Eric* *Hoffmann*
Senior Engineering Manager, Quality Engineering & Operations
Tigera
eric@tigera.io | M: +1 415-612-9546 <+1-415-612-9546> | @2ffs2nns
<http://twitter.com/twitterhandle>
Follow us: Blog <https://blog.tigera.io/> | Twitter
<https://twitter.com/tigeraio> | LinkedIn
<https://www.linkedin.com/company/tigera/>

Zero Trust Network Security & Continuous Compliance for Kubernetes Platforms
<https://tigera.io/>

**Comment by mogren** [comment]
@2ffs2nns Any chance this might get done this week? It would be great to have this updated. 

Could you maybe recommend what Calico version we should use in the next CNI release?

**Comment by mogren** [comment]
Updated this PR in #368 instead

**Pull request closed without merging**
